var Planets;
(function (Planets) {
    Planets[Planets["Mercury"] = 0] = "Mercury";
    Planets[Planets["Venus"] = 1] = "Venus";
    Planets[Planets["Earth"] = 2] = "Earth";
    Planets[Planets["Mars"] = 3] = "Mars";
    Planets[Planets["Jupiter"] = 4] = "Jupiter";
    Planets[Planets["Saturn"] = 5] = "Saturn";
    Planets[Planets["Uranus"] = 6] = "Uranus";
    Planets[Planets["Neptune"] = 7] = "Neptune";
    Planets[Planets["Pluto"] = 8] = "Pluto";
})(Planets || (Planets = {}));
// console.log(Planets.Mercury);
// console.log(Planets.Venus);
// console.log(Planets.Earth);
// console.log(Planets.Mars);
// console.log(Planets.Jupiter);
// console.log(Planets.Saturn);
// console.log(Planets.Uranus);
// console.log(Planets.Neptune);
// console.log(Planets.Pluto);
console.log(Planets[0]);
console.log(Planets[1]);
console.log(Planets[2]);
console.log(Planets[3]);
console.log(Planets[4]);
console.log(Planets[5]);
console.log(Planets[6]);
console.log(Planets[7]);
console.log(Planets[8]);
console.warn("=============================================================");
var Directions;
(function (Directions) {
    Directions[Directions["North"] = 1] = "North";
    Directions[Directions["East"] = 2] = "East";
    Directions[Directions["South"] = 3] = "South";
    Directions[Directions["West"] = 4] = "West";
})(Directions || (Directions = {}));
console.log(Directions.North);
console.log(Directions.East);
console.log(Directions.South);
console.log(Directions.West);
console.log(Directions[1]);
console.log(Directions[2]);
console.log(Directions[3]);
console.log(Directions[4]);
